version: "3"

services:
  app:
    build:
      context: ./docker/fpm
      dockerfile: Dockerfile
    image: working-with-string/php
    container_name: working-with-string-app
    restart: unless-stopped
    volumes:
      - ./:/var/www